name: Build RBR50v2 Firmware

on:
  workflow_dispatch: # Allows you to manually trigger it from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        

      - name: Checkout Git from PR cptpcrd for RBR50v2 Device Tree
        run: |
          git fetch origin pull/22321/head:pr-22321
          git checkout pr-22321
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison gawk gettext \
            git libncurses5-dev libssl-dev rsync unzip zlib1g-dev

      - name: Update & Install Feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Configure Target (ipq40xx / RBR50v2)
        run: |
          echo "CONFIG_TARGET_ipq40xx=y" > .config
          echo "CONFIG_TARGET_ipq40xx_generic=y" >> .config
          echo "CONFIG_TARGET_DEVICE_ipq40xx_generic_DEVICE_netgear_rbr50-v2=y" >> .config
          make defconfig

      - name: Download Sources
        run: make download -j4

      - name: Compile Firmware
        run: make -j$(nproc)


      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-ipq40xx-generic-full-build
          path: bin/targets/ipq40xx/generic/
          if-no-files-found: error
